name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *"    # Runs every 24 hours
  workflow_dispatch:          # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: chottosid
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
